[bootstrap.packages]
"brew:ghq" = "latest"
"brew:trash" = "latest"
"brew:herdr" = "latest"
"brew-cask:ghostty" = "latest"

[bootstrap.macos.defaults]
"com.apple.screencapture" = { disable-shadow = true, location = "~/Desktop/Screenshots", name = "SS" }
"com.apple.finder" = { AppleShowAllFiles = true }

[bootstrap.hooks.post-defaults]
run = "killall Finder SystemUIServer || true"

[dotfiles]
"~/.config/ghostty/config" = { source = "config/ghostty/config", mode = "symlink" }
"~/.config/herdr/config.toml" = { source = "config/herdr/config.toml", mode = "symlink" }
"~/.config/karabiner/karabiner.json" = { source = "config/karabiner/karabiner.json", mode = "symlink" }
"~/.gitconfig" = { source = ".gitconfig", mode = "symlink" }
"~/.vimrc" = { source = ".vimrc", mode = "symlink" }
"~/.zshrc" = { source = ".zshrc", mode = "symlink" }
